/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionbancaire;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i Ilo
 */
public class Retrait extends javax.swing.JFrame {

    /**
     * Creates new form Retrait
     */
    public Retrait() {
        initComponents();
        tableRetrait();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con1;
    PreparedStatement ajoutRetrait;
    PreparedStatement ancienSolde;
    PreparedStatement nouveauSolde;
    PreparedStatement ancienRetrait;

    private void tableRetrait() {
        int c;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutRetrait = con1.prepareStatement("SELECT * FROM Retrait");
            ResultSet rs = ajoutRetrait.executeQuery();
            ResultSetMetaData Res = rs.getMetaData();
            c = Res.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) tableRetrait.getModel();
            Df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("NumCheque"));
                    v2.add(rs.getString("NumCompte"));
                    v2.add(rs.getInt("MontantRetrait"));
                    v2.add(rs.getString("DateRetrait"));
                }
                Df.addRow(v2);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        numCheque = new javax.swing.JLabel();
        numCompte = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        numCompteText = new javax.swing.JTextField();
        montantText = new javax.swing.JTextField();
        numCheqText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        montant = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRetrait = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        solde = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numCheque.setText("Numéro chèque");

        numCompte.setText("Numéro Compte");

        date.setText("Date de Retrait");

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        montant.setText("Montant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date)
                            .addComponent(montant))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montantText)
                            .addComponent(dateText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCheque)
                            .addComponent(numCompte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCompteText)
                            .addComponent(numCheqText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numCheqText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCheque))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCompte)
                    .addComponent(numCompteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montant)
                    .addComponent(montantText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel5.setText("Etat de situation des retraits");

        tableRetrait.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numéro chèque", "Numéro Compte", "Montant", "Date de retrait"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableRetrait.setName("tableRetrait"); // NOI18N
        tableRetrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRetraitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRetrait);

        jLabel6.setText("Effectif : ");

        solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldeActionPerformed(evt);
            }
        });

        jMenu1.setText("Gestion Bancaire");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Client");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Versement");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Retrait");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Virement");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Bilan");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Histogramme");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(solde, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(solde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numcompte = numCompteText.getText();
        String numCheque = numCheqText.getText();
        String date = dateText.getText();
        String montant = montantText.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutRetrait = con1.prepareStatement("INSERT INTO Retrait(NumCompte,NumCheque,DateRetrait,MontantRetrait) VALUES ('" + numcompte + "','" + numCheque + "','" + date + "','" + montant + "')");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+numcompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
         
           
            int nouveauSoldeInt=ancienSoldeInt-Integer.parseInt(montant);
            String b=Integer.toString(nouveauSoldeInt);
            solde.setText(b);
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+numcompte+"'");
            ajoutRetrait.executeUpdate();
            nouveauSolde.executeUpdate();
            JOptionPane.showMessageDialog(this, "Retrait Effectué");

            
            numCheqText.setText("");
            montantText.setText("");
            dateText.setText("");
            numCompteText.setText("");
            numCheqText.requestFocus();
            tableRetrait();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)tableRetrait.getModel();
        int selectedIndex=tableRetrait.getSelectedRow();
        try {                                       
        String numcompte = numCompteText.getText();
        String numCheque = numCheqText.getText();
        String date = dateText.getText();
        String montant = montantText.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            ajoutRetrait=con1.prepareStatement("UPDATE Retrait SET NumCompte='"+numcompte+"',NumCheque='"+numCheque+"',DateRetrait='"+date+"',MontantRetrait='"+montant+"' WHERE NumCheque='"+numCheque+"'");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+numcompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
            ancienRetrait=con1.prepareStatement("SELECT MontantRetrait FROM retrait WHERE NumCheque='"+numCheque+"'");
            ResultSet rs2=ancienRetrait.executeQuery();
            int ancienRetraitInt=0;
            while(rs2.next()){
                ancienRetraitInt=rs2.getInt("MontantRetrait");
            }
           
            int nouveauSoldeInt=ancienSoldeInt-Integer.parseInt(montant)+ancienRetraitInt;
            String b=Integer.toString(nouveauSoldeInt);
            solde.setText(b);
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+numcompte+"'");
            nouveauSolde.executeUpdate();
            ajoutRetrait.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Retrait Modifie");
            
            numCheqText.setText("");
            montantText.setText("");
            dateText.setText("");
            numCompteText.setText("");
            numCheqText.requestFocus();
            tableRetrait();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableRetraitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRetraitMouseClicked

        DefaultTableModel Df = (DefaultTableModel) tableRetrait.getModel();
        int selectedIndex = tableRetrait.getSelectedRow();

        numCheqText.setText(Df.getValueAt(selectedIndex, 0).toString());
        montantText.setText(Df.getValueAt(selectedIndex, 2).toString());
        dateText.setText(Df.getValueAt(selectedIndex, 3).toString());
        numCompteText.setText(Df.getValueAt(selectedIndex, 1).toString());      // TODO add your handling code here:
    }//GEN-LAST:event_tableRetraitMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)tableRetrait.getModel();
        int selectedIndex=tableRetrait.getSelectedRow();
        try {
            String numCheque = numCheqText.getText();
            String numcompte = numCompteText.getText();
            int dialogResult=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce client","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION)
            {
              Class.forName("com.mysql.cj.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            ajoutRetrait=con1.prepareStatement("DELETE FROM Retrait WHERE NumCheque='"+numCheque+"'");ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+numcompte+"'");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+numcompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
            ancienRetrait=con1.prepareStatement("SELECT MontantRetrait FROM retrait WHERE NumCheque='"+numCheque+"'");
            ResultSet rs2=ancienRetrait.executeQuery();
            int ancienRetraitInt=0;
            while(rs2.next()){
                ancienRetraitInt=rs2.getInt("MontantRetrait");
            }
           
            int nouveauSoldeInt=ancienSoldeInt+ancienRetraitInt;
            String b=Integer.toString(nouveauSoldeInt);
            solde.setText(b);
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+numcompte+"'");
            nouveauSolde.executeUpdate();
            ajoutRetrait.executeUpdate();
            JOptionPane.showMessageDialog(this, "Retrait Supprime");
            
            
            numCheqText.setText("");
            montantText.setText("");
            dateText.setText("");
            numCompteText.setText("");
            numCheqText.requestFocus();
            tableRetrait(); 
            }
           
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retrait().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel montant;
    private javax.swing.JTextField montantText;
    private javax.swing.JTextField numCheqText;
    private javax.swing.JLabel numCheque;
    private javax.swing.JLabel numCompte;
    private javax.swing.JTextField numCompteText;
    private javax.swing.JTextField solde;
    private javax.swing.JTable tableRetrait;
    // End of variables declaration//GEN-END:variables
}
