/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionbancaire;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i Ilo
 */
public class Versement extends javax.swing.JFrame {

    /**
     * Creates new form Versement
     */
    public Versement() {
        initComponents();
        tableVersement();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con1;
    PreparedStatement ajoutVersement;
    PreparedStatement ancienSolde;
    PreparedStatement nouveauSolde;
    PreparedStatement ancienVersement;

    private void tableVersement() {
        int c;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutVersement = con1.prepareStatement("SELECT * FROM Versement");
            ResultSet rs = ajoutVersement.executeQuery();
            ResultSetMetaData Res = rs.getMetaData();
            c = Res.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) tableVersement.getModel();
            Df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("NumVersement"));
                    v2.add(rs.getString("DateVersement"));
                    v2.add(rs.getInt("Montant"));
                    v2.add(rs.getString("NumCompte"));
                }
                Df.addRow(v2);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumVersement = new javax.swing.JTextField();
        DateVersement = new javax.swing.JTextField();
        Montant = new javax.swing.JTextField();
        NumCompte = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVersement = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numéro versement");

        jLabel2.setText("Date versement");

        jLabel3.setText("Montant");

        jLabel4.setText("Numéro Compte");

        NumVersement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumVersementActionPerformed(evt);
            }
        });

        NumCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCompteActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumVersement, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(NumCompte)
                            .addComponent(Montant)
                            .addComponent(DateVersement))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(NumVersement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(DateVersement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        tableVersement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numéro versement", "Date versement", "Montant", "Numéro compte"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableVersement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVersementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVersement);

        jMenu1.setText("Gestion Bancaire");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Client");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Versement");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Retrait");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Virement");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Bilan");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Histogramme");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumVersementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumVersementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumVersementActionPerformed

    private void NumCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCompteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        String vNumVersement = NumVersement.getText();
        String vDateVersement = DateVersement.getText();
        String vMontant = Montant.getText();
        String vNumCompte = NumCompte.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutVersement = con1.prepareStatement("INSERT INTO Versement(NumVersement,DateVersement,Montant,NumCompte) VALUES ('" + vNumVersement + "','" + vDateVersement + "','" + vMontant + "','" + vNumCompte + "')");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumCompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
         
           
            int nouveauSoldeInt=ancienSoldeInt+Integer.parseInt(vMontant);
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+vNumCompte+"'");
            ajoutVersement.executeUpdate();
            nouveauSolde.executeUpdate();
            JOptionPane.showMessageDialog(this, "Versement Effectué");

            
            NumVersement.setText("");
            DateVersement.setText("");
            Montant.setText("");
            NumCompte.setText("");
            NumVersement.requestFocus();
            tableVersement();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)tableVersement.getModel();
        int selectedIndex=tableVersement.getSelectedRow();
        try {                                      
        String vNumVersement = NumVersement.getText();
        String vDateVersement = DateVersement.getText();
        String vMontant = Montant.getText();
        String vNumCompte = NumCompte.getText();
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            ajoutVersement=con1.prepareStatement("UPDATE Versement SET NumCompte='"+vNumCompte+"',NumVersement='"+vNumVersement+"',DateVersement='"+vDateVersement+"',Montant='"+vMontant+"' WHERE NumVersement='"+vNumVersement+"'");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumCompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
            ancienVersement=con1.prepareStatement("SELECT Montant FROM Versement WHERE NumVersement='"+vNumVersement+"'");
            ResultSet rs2=ancienVersement.executeQuery();
            int ancienVersementInt=0;
            while(rs2.next()){
                ancienVersementInt=rs2.getInt("Montant");
            }
           
            int nouveauSoldeInt=ancienSoldeInt+Integer.parseInt(vMontant)-ancienVersementInt;
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+vNumCompte+"'");
            nouveauSolde.executeUpdate();
            ajoutVersement.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Retrait Modifie");
            
            NumVersement.setText("");
            DateVersement.setText("");
            Montant.setText("");
            NumCompte.setText("");
            NumVersement.requestFocus();
            tableVersement();
            
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableVersementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVersementMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) tableVersement.getModel();
        int selectedIndex = tableVersement.getSelectedRow();

        NumVersement.setText(Df.getValueAt(selectedIndex, 0).toString());
        DateVersement.setText(Df.getValueAt(selectedIndex, 1).toString());
        Montant.setText(Df.getValueAt(selectedIndex, 2).toString());
        NumCompte.setText(Df.getValueAt(selectedIndex, 3).toString());  
    }//GEN-LAST:event_tableVersementMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)tableVersement.getModel();
        int selectedIndex=tableVersement.getSelectedRow();
        try {
                String vNumVersement = NumVersement.getText();
                String vNumCompte = NumCompte.getText();
            int dialogResult=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce client","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION)
            {
              Class.forName("com.mysql.cj.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            ajoutVersement=con1.prepareStatement("DELETE FROM Versement WHERE NumVersement='"+vNumVersement+"'");
            ancienSolde = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumCompte+"'");
            ResultSet rs = ancienSolde.executeQuery();
            int ancienSoldeInt=0;
             while (rs.next()) {
                    ancienSoldeInt=rs.getInt("Solde");
            }
            ancienVersement=con1.prepareStatement("SELECT Montant FROM versement WHERE NumVersement='"+vNumVersement+"'");
            ResultSet rs2=ancienVersement.executeQuery();
            int ancienVersementInt=0;
            while(rs2.next()){
                ancienVersementInt=rs2.getInt("Montant");
            }
           
            int nouveauSoldeInt=ancienSoldeInt-ancienVersementInt;
            nouveauSolde = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeInt+"' WHERE NumCompte='"+vNumCompte+"'");
            nouveauSolde.executeUpdate();
            ajoutVersement.executeUpdate();
            JOptionPane.showMessageDialog(this, "Versement Supprime");
            
            
            NumVersement.setText("");
            DateVersement.setText("");
            Montant.setText("");
            NumCompte.setText("");
            NumVersement.requestFocus();
            tableVersement();
            }
           
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Versement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Versement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Versement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Versement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Versement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateVersement;
    private javax.swing.JTextField Montant;
    private javax.swing.JTextField NumCompte;
    private javax.swing.JTextField NumVersement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVersement;
    // End of variables declaration//GEN-END:variables
}
