/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionbancaire;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i Ilo
 */
public class Virement extends javax.swing.JFrame {

    /**
     * Creates new form Virement
     */
    public Virement() {
        initComponents();
        tableVirement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con1;
    Connection con2;
    Connection con0;
    PreparedStatement ajoutVirement;
    PreparedStatement ancienSoldeReceveur;
    PreparedStatement nouveauSoldeReceveur;
    PreparedStatement ancienSoldeEnvoyeur;
    PreparedStatement nouveauSoldeEnvoyeur;
    PreparedStatement ancienVirement;

    private void tableVirement() {
        int c;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutVirement = con1.prepareStatement("SELECT * FROM Virement");
            ResultSet rs = ajoutVirement.executeQuery();
            ResultSetMetaData Res = rs.getMetaData();
            c = Res.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) tableVirement.getModel();
            Df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 1; a <= c; a++) {
                    v2.add(rs.getString("NumVirement"));
                    v2.add(rs.getString("DateVirement"));
                    v2.add(rs.getInt("Montant"));
                    v2.add(rs.getString("NumEnvoyeur"));
                    v2.add(rs.getString("NumReceveur"));
                }
                Df.addRow(v2);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Numreceveur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumVirement = new javax.swing.JTextField();
        DateVirement = new javax.swing.JTextField();
        Montant = new javax.swing.JTextField();
        NumEnvoyeur = new javax.swing.JTextField();
        NumReceveur = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVirement = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numéro Virement");

        jLabel2.setText("Date Virement");

        jLabel3.setText("Montant");

        jLabel4.setText("Numéro envoyeur");

        jLabel5.setText("Numéro receveur");

        NumEnvoyeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEnvoyeurActionPerformed(evt);
            }
        });

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.setEnabled(false);
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setText("Supprimer");
        supprimer.setEnabled(false);
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumreceveurLayout = new javax.swing.GroupLayout(Numreceveur);
        Numreceveur.setLayout(NumreceveurLayout);
        NumreceveurLayout.setHorizontalGroup(
            NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumreceveurLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumreceveurLayout.createSequentialGroup()
                        .addComponent(ajouter)
                        .addGap(58, 58, 58)
                        .addComponent(modifier)
                        .addGap(44, 44, 44)
                        .addComponent(supprimer))
                    .addGroup(NumreceveurLayout.createSequentialGroup()
                        .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumVirement, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(DateVirement)
                            .addComponent(Montant)
                            .addComponent(NumEnvoyeur)
                            .addComponent(NumReceveur))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        NumreceveurLayout.setVerticalGroup(
            NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumreceveurLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumVirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DateVirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumEnvoyeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NumReceveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(NumreceveurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tableVirement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NumVirement", "DateVirement", "Montant", "NumEnvoyeur", "NumReceveur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVirementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVirement);

        jLabel6.setText("VIREMENT");

        jMenu2.setText("Client");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Versement");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Retrait");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Virement");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Numreceveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Numreceveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumEnvoyeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEnvoyeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEnvoyeurActionPerformed

    private void tableVirementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVirementMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) tableVirement.getModel();
        int selectedIndex = tableVirement.getSelectedRow();

        NumVirement.setText(Df.getValueAt(selectedIndex, 0).toString());
        DateVirement.setText(Df.getValueAt(selectedIndex, 1).toString());
        Montant.setText(Df.getValueAt(selectedIndex, 2).toString());
        NumEnvoyeur.setText(Df.getValueAt(selectedIndex, 3).toString());
        NumReceveur.setText(Df.getValueAt(selectedIndex, 4).toString());
        
        ajouter.setEnabled(false);
        modifier.setEnabled(true);
        supprimer.setEnabled(true);
        NumVirement.setEnabled(false);
        NumEnvoyeur.setEnabled(false);
        NumReceveur.setEnabled(false);
    }//GEN-LAST:event_tableVirementMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:
        String vNumVirement = NumVirement.getText();
        String vDateVirement = DateVirement.getText();
        String vMontant = Montant.getText();
        String vNumEnvoyeur = NumEnvoyeur.getText();
        String vNumReceveur = NumReceveur.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutVirement = con1.prepareStatement("INSERT INTO Virement(NumVirement,DateVirement,Montant,NumEnvoyeur,NumReceveur) VALUES ('" + vNumVirement + "','" + vDateVirement + "','" + vMontant + "','" + vNumEnvoyeur + "','" + vNumReceveur + "')");
            ancienSoldeEnvoyeur = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumEnvoyeur+"'");
            ResultSet rs = ancienSoldeEnvoyeur.executeQuery();
            int ancienSoldeEnvoyeurInt=0;
             if (rs.next()) {
                    ancienSoldeEnvoyeurInt=rs.getInt("Solde");
            }
         
           int nouveauSoldeEnvoyeurInt=ancienSoldeEnvoyeurInt-Integer.parseInt(vMontant);
           
           
            nouveauSoldeEnvoyeur = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeEnvoyeurInt+"' WHERE NumCompte='"+vNumEnvoyeur+"'");
            ancienSoldeReceveur = con2.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumReceveur+"'");
            ResultSet rs2 = ancienSoldeReceveur.executeQuery();
            int ancienSoldeReceveurInt=0;
             if (rs2.next()) {
                    ancienSoldeReceveurInt=rs2.getInt("Solde");
            }
         
           int nouveauSoldeReceveurInt=ancienSoldeReceveurInt+Integer.parseInt(vMontant);
            nouveauSoldeReceveur = con2.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeReceveurInt+"' WHERE NumCompte='"+vNumReceveur+"'");
            
            
            ajoutVirement.executeUpdate();
            nouveauSoldeEnvoyeur.executeUpdate();
            nouveauSoldeReceveur.executeUpdate();
            JOptionPane.showMessageDialog(this, "Virement Effectué");

            
            NumVirement.setText("");
            DateVirement.setText("");
            Montant.setText("");
            NumEnvoyeur.setText("");
            NumReceveur.setText("");
            NumVirement.requestFocus();
            tableVirement();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_ajouterActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)tableVirement.getModel();
        int selectedIndex=tableVirement.getSelectedRow();
        try {
        String vNumVirement = NumVirement.getText();
        String vDateVirement = DateVirement.getText();
        String vMontant = Montant.getText();
        String vNumEnvoyeur = NumEnvoyeur.getText();
        String vNumReceveur = NumReceveur.getText();
            int dialogResult=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer ce client","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult==JOptionPane.YES_OPTION)
            {
              Class.forName("com.mysql.cj.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            ajoutVirement=con1.prepareStatement("DELETE FROM Virement WHERE NumVirement='"+vNumVirement+"'");
            ancienSoldeEnvoyeur = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumEnvoyeur+"'");
            ResultSet rs = ancienSoldeEnvoyeur.executeQuery();
            int ancienSoldeEnvoyeurInt=0;
             if (rs.next()) {
                    ancienSoldeEnvoyeurInt=rs.getInt("Solde");
            }
         
           int nouveauSoldeEnvoyeurInt=ancienSoldeEnvoyeurInt+Integer.parseInt(vMontant);
           
           
            nouveauSoldeEnvoyeur = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeEnvoyeurInt+"' WHERE NumCompte='"+vNumEnvoyeur+"'");
            ancienSoldeReceveur = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumReceveur+"'");
            ResultSet rs2 = ancienSoldeReceveur.executeQuery();
            int ancienSoldeReceveurInt=0;
             while (rs2.next()) {
                    ancienSoldeReceveurInt=rs2.getInt("Solde");
            }
         
           int nouveauSoldeReceveurInt=ancienSoldeReceveurInt-Integer.parseInt(vMontant);
            nouveauSoldeReceveur = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeReceveurInt+"' WHERE NumCompte='"+vNumReceveur+"'");
            
            
            ajoutVirement.executeUpdate();
            nouveauSoldeEnvoyeur.executeUpdate();
            nouveauSoldeReceveur.executeUpdate();
            JOptionPane.showMessageDialog(this, "Virement Effectué");

            
            NumVirement.setText("");
            DateVirement.setText("");
            Montant.setText("");
            NumEnvoyeur.setText("");
            NumReceveur.setText("");
            NumVirement.requestFocus();
            tableVirement();
            }
           
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        ajouter.setEnabled(true);
        modifier.setEnabled(false);
        supprimer.setEnabled(false);
        NumVirement.setEnabled(true);
        NumEnvoyeur.setEnabled(true);
        NumReceveur.setEnabled(true);
    }//GEN-LAST:event_supprimerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        String vNumVirement = NumVirement.getText();
        String vDateVirement = DateVirement.getText();
        String vMontant = Montant.getText();
        String vNumEnvoyeur = NumEnvoyeur.getText();
        String vNumReceveur = NumReceveur.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            con0 = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionbancaire?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
            ajoutVirement=con1.prepareStatement("UPDATE Virement SET DateVirement='"+vDateVirement+"',Montant='"+vMontant+"' WHERE NumVirement='"+vNumVirement+"'");
            ancienVirement=con0.prepareStatement("SELECT Montant FROM Virement WHERE NumVirement='"+vNumVirement+"'");
            ResultSet rs0 = ancienVirement.executeQuery();
            int ancienVirementInt=0;
             if (rs0.next()) {
                    ancienVirementInt=rs0.getInt("Montant");
            }
            ancienSoldeEnvoyeur = con1.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumEnvoyeur+"'");
            ResultSet rs = ancienSoldeEnvoyeur.executeQuery();
            int ancienSoldeEnvoyeurInt=0;
             if (rs.next()) {
                    ancienSoldeEnvoyeurInt=rs.getInt("Solde");
            }
         
           int nouveauSoldeEnvoyeurInt=ancienSoldeEnvoyeurInt-Integer.parseInt(vMontant)+ancienVirementInt;
           
           
            nouveauSoldeEnvoyeur = con1.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeEnvoyeurInt+"' WHERE NumCompte='"+vNumEnvoyeur+"'");
            ancienSoldeReceveur = con2.prepareStatement("SELECT * FROM client WHERE NumCompte='"+vNumReceveur+"'");
            ResultSet rs2 = ancienSoldeReceveur.executeQuery();
            int ancienSoldeReceveurInt=0;
             if (rs2.next()) {
                    ancienSoldeReceveurInt=rs2.getInt("Solde");
            }
         
           int nouveauSoldeReceveurInt=ancienSoldeReceveurInt+Integer.parseInt(vMontant)-ancienVirementInt;
            nouveauSoldeReceveur = con2.prepareStatement("UPDATE Client SET Solde='"+nouveauSoldeReceveurInt+"' WHERE NumCompte='"+vNumReceveur+"'");
            
            
            ajoutVirement.executeUpdate();
            nouveauSoldeEnvoyeur.executeUpdate();
            nouveauSoldeReceveur.executeUpdate();
            JOptionPane.showMessageDialog(this, "Virement Modifié");

            
            NumVirement.setText("");
            DateVirement.setText("");
            Montant.setText("");
            NumEnvoyeur.setText("");
            NumReceveur.setText("");
            NumVirement.requestFocus();
            tableVirement();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } 
        ajouter.setEnabled(true);
        modifier.setEnabled(false);
        supprimer.setEnabled(false);
        NumVirement.setEnabled(true);
        NumEnvoyeur.setEnabled(true);
        NumReceveur.setEnabled(true);
    }//GEN-LAST:event_modifierActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new Client().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        new Versement().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new Retrait().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        new Versement().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Virement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Virement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateVirement;
    private javax.swing.JTextField Montant;
    private javax.swing.JTextField NumEnvoyeur;
    private javax.swing.JTextField NumReceveur;
    private javax.swing.JTextField NumVirement;
    private javax.swing.JPanel Numreceveur;
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tableVirement;
    // End of variables declaration//GEN-END:variables
}
